import { useState, useEffect } from 'react';
import axios from 'axios';

// Define what a Node looks like based on your JSON
interface Node {
  address: string;
    pubkey: string;
      version: string;
        uptime: number;
          is_public: boolean;
            storage_used: number;
            }

            export default function Home() {
              const [nodes, setNodes] = useState<Node[]>([]);
                const [loading, setLoading] = useState(true);
                  const [error, setError] = useState('');
                    const [lastUpdated, setLastUpdated] = useState('');

                      // Function to fetch data
                        const fetchStats = async () => {
                            setLoading(true);
                                setError('');
                                    try {
                                          const res = await axios.get('/api/stats');
                                                
                                                      // The nodes are inside res.data.result.pods
                                                            if (res.data.result && res.data.result.pods) {
                                                                    setNodes(res.data.result.pods);
                                                                            setLastUpdated(new Date().toLocaleTimeString());
                                                                                  } else {
                                                                                          setError('Invalid data format received');
                                                                                                }
                                                                                                    } catch (err: any) {
                                                                                                          setError('Failed to fetch data: ' + err.message);
                                                                                                              } finally {
                                                                                                                    setLoading(false);
                                                                                                                        }
                                                                                                                          };

                                                                                                                            // Run on load
                                                                                                                              useEffect(() => {
                                                                                                                                  fetchStats();
                                                                                                                                    }, []);

                                                                                                                                      return (
                                                                                                                                          <div className="min-h-screen bg-black text-green-500 font-mono p-4 md:p-8">
                                                                                                                                                {/* HEADER */}
                                                                                                                                                      <header className="flex flex-col md:flex-row justify-between items-center mb-8 border-b border-green-900 pb-4">
                                                                                                                                                              <div>
                                                                                                                                                                        <h1 className="text-3xl font-bold tracking-tighter">XANDEUM PULSE</h1>
                                                                                                                                                                                  <p className="text-xs text-green-700 mt-1">REAL-TIME pNODE MONITOR</p>
                                                                                                                                                                                          </div>
                                                                                                                                                                                                  
                                                                                                                                                                                                          <div className="flex items-center gap-4 mt-4 md:mt-0">
                                                                                                                                                                                                                    <div className="text-right">
                                                                                                                                                                                                                                <div className="text-xs text-green-700">STATUS</div>
                                                                                                                                                                                                                                            <div className="text-sm font-bold animate-pulse">
                                                                                                                                                                                                                                                          {loading ? 'SCANNING...' : 'ONLINE'}
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                          <button 
                                                                                                                                                                                                                                                                                                      onClick={fetchStats}
                                                                                                                                                                                                                                                                                                                  className="px-4 py-2 border border-green-700 hover:bg-green-900 transition text-xs uppercase"
                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                        Refresh
                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                                                                                                                                                      {/* STATS BAR */}
                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-green-900/10 border border-green-900/50 p-4">
                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-xs text-green-700">ACTIVE NODES</div>
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-2xl font-bold">{nodes.length}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-green-900/10 border border-green-900/50 p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-xs text-green-700">LAST UPDATE</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-xl font-bold">{lastUpdated || '--:--'}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* ERROR MESSAGE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-red-900/20 border border-red-500 text-red-500 p-4 mb-8 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ⚠️ ERROR: {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* NODE GRID */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-center py-20 animate-pulse text-green-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [ FETCHING NETWORK TOPOLOGY... ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {nodes.map((node, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={i} className="border border-green-900/50 bg-black hover:border-green-500 transition p-4 relative group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="absolute top-2 right-2 w-2 h-2 rounded-full bg-green-500 shadow-[0_0_10px_#22c55e]"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-[10px] text-green-700 uppercase">Address</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-sm truncate font-bold text-white">{node.address}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-2 gap-2 text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-green-700 block">VERSION</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-gray-300">{node.version}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-green-700 block">UPTIME</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-gray-300">{(node.uptime / 3600).toFixed(1)}h</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="col-span-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-green-700 block">STORAGE</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="w-full bg-green-900/30 h-1 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="bg-green-500 h-full" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ width: `${Math.min((node.storage_used / 1000000) * 100, 100)}%` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }